# Generated by Django 4.1.7 on 2023-02-20 14:42

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_alter_job_position"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="position",
            new_name="positions",
        ),
        migrations.AlterField(
            model_name="job",
            name="lastDate",
            field=models.DateTimeField(default=job.models.return_date_time),
        ),
    ]
