# Generated by Django 4.1.7 on 2023-02-20 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0003_rename_position_job_positions_alter_job_lastdate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="point",
        ),
    ]
