# Generated by Django 4.1.7 on 2023-03-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0005_candidatesapplied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="jobType",
            field=models.CharField(
                choices=[
                    ("Permanent", "Permanent"),
                    ("Temporary", "Temporary"),
                    ("Internship", "Internship"),
                ],
                default="Permanent",
                max_length=10,
            ),
        ),
    ]
