# Generated by Django 4.1.7 on 2023-03-17 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0007_job_point"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="point",
        ),
    ]
