# Generated by Django 4.1.7 on 2023-03-19 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0009_job_point"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="point",
        ),
    ]
