# Generated by Django 4.1.7 on 2023-04-03 23:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0021_job_point"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="point",
        ),
    ]
