# Generated by Django 4.1.7 on 2023-04-04 08:39

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0022_remove_job_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326
            ),
        ),
    ]
